version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: tcp://dind:2375

  dind:
    image: docker:dind
    privileged: true
    expose:
      - "2375"
    environment:
      DOCKER_TLS_CERTDIR: ""

version: '3'

services:
  dind:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    depends_on:
      - dind
    environment:
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8081:8080
      - 50000:50000

volumes:
  docker-certs-ca:
  docker-certs-client:
  jenkins-data:
